---
gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - "/vendor/"
title: Deepwonwoo
subtitle: To the infinity and beyond
email: deepwonwoo@kakao.com
name: Wonwoo Choi
description: "Deepwonwoo의 기술블로그"
baseurl: ""
url: https://deepwonwoo.github.io/
plugins_dir:
  - jekyll-sitemap
cover: "/assets/header_image.png"
logo: "/assets/deepmind_logo.jpg"
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
highlightjs_theme: monokai-sublime
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  comments: true
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
disqus_shortname: zoomKoding
ga_tracking_id: UA-83878761-1
descriptions:
  - cat: jekyll
    desc: Posts describing Jekyll setup techniques.
social:
  - name: GitHub
    icon: github
    username: deepwonwoo
    url: https://github.com/deepwonwoo
    desc: Fork me on GitHub
    share: false
protocols:
  fb_image: "/assets/deepmind_logo.jpg"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: "/assets/deepmind_logo.jpg"
  os_repo: https://github.com/bencentra/centrarium.com
  os_rcs_type: git
  os_src: git@github.com:bencentra/centrarium.com.git
